### ISSUE TITLE
有些关于Spring和MyBatis的疑惑

### ISSUE THREAD

**Issue by GYiyouth** [SmileNJsx/SSMTemplate#1]
你好，我在学这两个框架的结合，目前有些不懂的地方，MyBatis我学的时候，都是用的配置文件，但是和Spring结合以后，感觉MyBatis完全不会用了。。。

**Comment by SmileNJsx** [comment]
不好意思，很晚看到，解决没有

**Comment by GYiyouth** [comment]
解决了，谢谢
